package com.imtae.gitcheck.retrofit.domain

data class User(
    var login: String = "",
    var id: Long = 0,
    var node_id: String = "",
    var avatar_url: String = "",
    var gravatar_id: String = "",
    var url: String = "",
    var html_url: String = "",
    var followers_url: String = "",
    var following_url: String = "",
    var gists_url: String = "",
    var starred_url: String = "",
    var subscriptions_url: String = "",
    var organizations_url: String = "",
    var repos_url: String = "",
    var events_url: String = "",
    var receivedEvents_url: String = "",
    var type: String = "",
    var site_admin: Boolean = false,
    var name: String = "",
    var company: String = "",
    var blog: String = "",
    var location: String = "",
    var email: Any? = null,
    var hireable: Any? = null,
    var bio: String = "",
    var public_repos: Long = 0,
    var public_gists: Long = 0,
    var followers: Long = 0,
    var following: Long = 0,
    var created_at: String = "",
    var updated_at: String = "",
    var code: Int = 0
)