package com.imtae.gitcheck.retrofit.domain

data class User(
    val login: String = "",
    val id: Long = 0,
    val node_id: String = "",
    val avatar_url: String = "",
    val gravatar_id: String = "",
    val url: String = "",
    val html_url: String = "",
    val followers_url: String = "",
    val following_url: String = "",
    val gists_url: String = "",
    val starred_url: String = "",
    val subscriptions_url: String = "",
    val organizations_url: String = "",
    val repos_url: String = "",
    val events_url: String = "",
    val receivedEvents_url: String = "",
    val type: String = "",
    val site_admin: Boolean = false,
    val name: String = "",
    val company: String = "",
    val blog: String = "",
    val location: String = "",
    val email: Any? = null,
    val hireable: Any? = null,
    val bio: String = "",
    val public_repos: Long = 0,
    val public_gists: Long = 0,
    val followers: Long = 0,
    val following: Long = 0,
    val created_at: String = "",
    val updated_at: String = "",
    val code: Int = 0
)